# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_desk',
            new_name='task_desc',
        ),
    ]
